# Generated by Django 6.1.1 on 2026-09-15 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('has_numbered_seats', models.BooleanField(default=False, verbose_name='places numérotées')),
                ('capacity', models.PositiveIntegerField(help_text='Utilisée pour les zones sans places numérotées ; ignorée si des sièges (Seat) sont définis pour cette section.', verbose_name='capacité')),
            ],
            options={
                'verbose_name': 'section',
                'verbose_name_plural': 'sections',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nom')),
                ('city', models.CharField(max_length=100, verbose_name='ville')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='adresse')),
            ],
            options={
                'verbose_name': 'lieu',
                'verbose_name_plural': 'lieux',
            },
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=150, verbose_name='nom affiché')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('mobile_money_account', models.CharField(blank=True, max_length=50, verbose_name='compte Mobile Money (reversement)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_profile', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'organisateur',
                'verbose_name_plural': 'organisateurs',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('starts_at', models.DateTimeField(verbose_name='date et heure de début')),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='brouillon', max_length=20, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ticketing.organizer', verbose_name='organisateur')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='ticketing.venue', verbose_name='lieu')),
            ],
            options={
                'verbose_name': 'événement',
                'verbose_name_plural': 'événements',
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='prix (FCFA)')),
                ('quota', models.PositiveIntegerField(verbose_name='quota disponible')),
                ('sales_start', models.DateTimeField(blank=True, null=True, verbose_name='ouverture des ventes')),
                ('sales_end', models.DateTimeField(blank=True, null=True, verbose_name='fin des ventes')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='ticketing.event', verbose_name='événement')),
                ('section', models.ForeignKey(blank=True, help_text='Optionnel : laisser vide pour un tarif non lié à une zone précise.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ticket_types', to='ticketing.section', verbose_name='section')),
            ],
            options={
                'verbose_name': 'tarif',
                'verbose_name_plural': 'tarifs',
                'ordering': ['event', 'price'],
            },
        ),
        migrations.AddField(
            model_name='section',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='ticketing.venue', verbose_name='lieu'),
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=10, verbose_name='rangée')),
                ('number', models.CharField(max_length=10, verbose_name='numéro')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='ticketing.section', verbose_name='section')),
            ],
            options={
                'verbose_name': 'siège',
                'verbose_name_plural': 'sièges',
                'ordering': ['row', 'number'],
                'unique_together': {('section', 'row', 'number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('venue', 'name')},
        ),
    ]
