# Generated by Django 6.1.1 on 2026-09-16 08:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_email', models.EmailField(max_length=254, verbose_name='e-mail acheteur')),
                ('buyer_phone', models.CharField(max_length=30, verbose_name='téléphone acheteur')),
                ('status', models.CharField(choices=[('creee', 'Créée'), ('paiement_en_attente', 'Paiement en attente'), ('payee', 'Payée'), ('billets_emis', 'Billets émis'), ('echouee', 'Échouée'), ('remboursee', 'Remboursée'), ('annulee', 'Annulée')], default='creee', max_length=30, verbose_name='statut')),
                ('amount_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='montant total (FCFA)')),
                ('payment_provider', models.CharField(blank=True, help_text="'simulator' ou 'cinetpay'", max_length=20, verbose_name='provider de paiement')),
                ('transaction_id', models.CharField(help_text='Généré à la création de la commande, transmis au provider de paiement.', max_length=64, unique=True, verbose_name='identifiant de transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mise à jour le')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='ticketing.event', verbose_name='événement')),
            ],
            options={
                'verbose_name': 'commande',
                'verbose_name_plural': 'commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20, verbose_name='provider')),
                ('provider_event_id', models.CharField(max_length=100, unique=True, verbose_name="identifiant d'événement (provider)")),
                ('event_type', models.CharField(blank=True, max_length=50, verbose_name="type d'événement")),
                ('signature_valid', models.BooleanField(verbose_name='signature valide')),
                ('raw_payload', models.JSONField(verbose_name='payload brut')),
                ('outcome', models.CharField(help_text="'applique', 'ignore', 'rejete' ou 'signature_invalide'.", max_length=20, verbose_name='résultat')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='reçu le')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='traité le')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_events', to='ticketing.order', verbose_name='commande')),
            ],
            options={
                'verbose_name': 'événement de paiement',
                'verbose_name_plural': 'événements de paiement',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_secret', models.CharField(default=uuid.uuid4, editable=False, max_length=64, unique=True, verbose_name='secret QR')),
                ('status', models.CharField(choices=[('valide', 'Valide'), ('scanne', 'Scanné'), ('annule', 'Annulé')], default='valide', max_length=20, verbose_name='statut')),
                ('scanned_at', models.DateTimeField(blank=True, null=True, verbose_name='scanné le')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='ticketing.order', verbose_name='commande')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_scanned', to=settings.AUTH_USER_MODEL, verbose_name='scanné par')),
                ('seat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='ticketing.seat', verbose_name='siège')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='ticketing.tickettype', verbose_name='tarif')),
            ],
            options={
                'verbose_name': 'billet',
                'verbose_name_plural': 'billets',
            },
        ),
    ]
