# Generated by Django 6.1.1 on 2026-09-16 (écrite à la main : makemigrations
# est interactif pour un ajout de champ non-nullable, indisponible en session
# non interactive — aucune ligne ticketing_organizer existante à ce jour,
# donc les valeurs par défaut ci-dessous ne s'appliquent à aucune donnée
# réelle, elles ne servent qu'à satisfaire le schéma de la migration).

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_order_paymentevent_ticket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizer_profile', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
        migrations.AddField(
            model_name='organizer',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True, verbose_name='e-mail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizer',
            name='password_hash',
            field=models.CharField(default='', editable=False, max_length=128, verbose_name='mot de passe (haché)'),
            preserve_default=False,
        ),
    ]
